apiVersion: v1
kind: Service
metadata:
  name: externalsvc
spec:
  ports:
   - name: nginx
     port: 9001
     protocol: TCP    
     targetPort: 80
     nodePort: 32180
   - name: multitool 
     port: 9002
     protocol: TCP    
     targetPort: 8080
  selector:
    app: multi
  type: NodePort 
