apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi
  name: multitool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:          
      - name: multitool
        image: wbitt/network-multitool  
        env:
        - name: HTTP_PORT
          value: "1180"   
        - name: HTTPS_PORT
          value: "11443"  
        ports:
        - containerPort: 1180   
          name: http-port
        - containerPort: 11443
          name: https-port  
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: nginx
  


          
      


          
