apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: daemonset
  name: multitooldaemonset
spec:
  selector:
    matchLabels:
      app: daemonset
  template:
    metadata:
      labels:
        app: daemonset
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule  
      containers:          
      - name: multitool
        image: wbitt/network-multitool  
        volumeMounts:
        - name: varlog
          mountPath: /multitool
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          
      


          
